### ISSUE TITLE
`prelude build run ...` times out

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/libraries#109] opened 2022-11-17 19:55 UTC
<img width="722" alt="CleanShot 2022-11-17 at 14 54 41@2x" src="https://user-images.githubusercontent.com/43142871/202545816-7d47ee05-f742-4d91-8ebd-5d1760ddec78.png">

payload is reaching the ECS cluster and running:
<img width="1792" alt="CleanShot 2022-11-17 at 14 54 51@2x" src="https://user-images.githubusercontent.com/43142871/202545961-3e952761-bfa9-40b9-a2c8-7314d23f1d0e.png">

Seems to timeout because compilation takes too long

**Comment by mireaulf** [comment] 2022-11-17 20:24
Duplicate of https://github.com/preludeorg/libraries/issues/101

**Closed by mireaulf** 2022-11-17 20:24 UTC
