### ISSUE TITLE
Scheduled Task error with install.ps1 

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/libraries#304] opened 2023-01-31 18:19 UTC
Getting this error from range when deploying probes:

Determining OS\n[+] Provisioning Detect Endpoint Token...\n[+] Downloading Probe...\n[+] Creating task\n[+] Task started\n[=] Detect setup complete\nRegister-ScheduledTask : No mapping between account names and security IDs was done.\r\n(14,8):UserId:\r\nAt C:\\Windows\\system32\\install.ps1:69 char:12\r\n+     [void](Register-ScheduledTask -TaskName $name -InputObject $task)\r\n+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (PS_ScheduledTask:Root\/Microsoft\/...S_ScheduledTask) [Register-ScheduledTa \r\n   sk], CimException\r\n    + FullyQualifiedErrorId : HRESULT 0x80070534,Register-ScheduledTask\r\n \r\n",0],["[+] Detect setup started\n[+] Determining OS\n[+] Provisioning Detect Endpoint Token...\n[+] Downloading Probe...\n[+] Creating task\n[+] Task started\n[=] Detect setup complete\nRegister-ScheduledTask : No mapping between account names and security IDs was done.\r\n(14,8):UserId:\r\nAt C:\\Windows\\system32\\install.ps1:69 char:12\r\n+     [void](Register-ScheduledTask -TaskName $name -InputObject $task)\r\n+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (PS_ScheduledTask:Root\/Microsoft\/...S_ScheduledTask) [Register-ScheduledTa \r\n   sk], CimException\r\n    + FullyQualifiedErrorId : HRESULT 0x80070534,Register-ScheduledTask\r\n \r\n",0]]]%

**Comment by makk94** [comment] 2023-01-31 18:29
dupe of a bug in the range/ repo (https://github.com/preludeorg/range/issues/15)

**Closed by makk94** 2023-01-31 18:29 UTC
